version: 0.2

phases:
  install:
    commands:
      # Installation commands go here
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo "Hello, World!"  # This will print "Hello World" to the logs
      - npm run-script build
  post_build:
    commands:
      # echo build completed
  artifacts:
    -index.js
    -test.js
