version: 0.2

cache:
  paths:
    - '/root/.m2/**/*'
    - 'node_modules/**/*'

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Preparing the build...
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - npm test
      - echo Notifying deployment service...
      - |
        curl -X POST -H "Content-Type: application/json" \
        -d '{"status": "success", "buildTime": "'$(date)'"}' \
        https://your-deployment-service.example.com/webhook

artifacts:
  files:
    - '**/*'
